version: '2'
services:
  postgres:
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6432:5432'
